//Auth
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
//API related
export const USER_SYNC_SUCCESS = 'USER_SYNC_SUCCESS'
//Challenge
export const SHOW_CREATE_CHALLENGE_VIEW = 'SHOW_CREATE_CHALLENGE_VIEW'
export const HIDE_CREATE_CHALLENGE_VIEW = 'HIDE_CREATE_CHALLENGE_VIEW'

export const SHOW_UPDATE_CHALLENGE_VIEW = 'SHOW_UPDATE_CHALLENGE_VIEW'
export const HIDE_UPDATE_CHALLENGE_VIEW = 'HIDE_UPDATE_CHALLENGE_VIEW'
